### ISSUE TITLE
feature: support for web sockets

### ISSUE THREAD

**Issue by sohlich** [sohlich/nats-proxy#2]
The initial idea is to create bidirectional subscription between proxy and client.

**Comment by joeblew99** [comment]
This would be awesome.

I just found your project tonight, and I am a heavy user of the Gin golang framework.

So I could probably help a bit on this if I get time.
For a current project I am working on I need browser clients to subscribe to topic events from nats.

**Comment by sohlich** [comment]
Well I was thinking of the implementation and It could be pretty straightforward. 

The proxy side will hold the WS sessions and also creates subscription to dedicated nats channel (witch could be something like url+sessionId of ws session). 

The client side should also receive the name of the channel and let the communication begin. There will be more work like notification of WS client events (client leave etc.) to be done. 

But  I think It might work. :)

**Comment by joeblew99** [comment]
Hey.

That project looks good too. I will try that one as it's very simple

**Comment by joeblew99** [comment]
I started to use nsq, because it allows embedding. So I will also adapt the example to that.

The embedding is very useful for me because then every microservices can run its own nsq, and it keeps things simple

**Comment by sohlich** [comment]
well need some more tests, but i think the elementary support is complete in protobuf branch
